server.port=8083

spring.kafka.bootstrap-servers=localhost:9092

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=carrym008@gmail.com
spring.mail.password=yyxn ufyo fuud xlrp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:postgresql://localhost:5432/log_intelligence
spring.datasource.username=jeel
spring.datasource.password=jeel123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
