# =========================
# KAFKA CONSUMER CONFIG
# =========================

# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Consumer group
spring.kafka.consumer.group-id=log-processor-v1
spring.kafka.consumer.auto-offset-reset=earliest

# Error-handling deserializers (prevents infinite crash loop)
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Actual delegate deserializers
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# TRUST our packages + DEFAULT CLASS FOR JSON
spring.kafka.consumer.properties.spring.json.trusted.packages=com.jeel.logging.*
spring.kafka.consumer.properties.spring.json.value.default.type=com.jeel.logging.common.events.LogIngestedEvent

